language: python
group: travis_latest
dist: xenial
sudo: true

# install xvfb virtual framebuffer - start commands with xvfb-run <command> - this we need for WINE
addons:
    apt:
        packages:
            - xvfb
            - winbind

service:
  - xvfb

script:
    - printenv
