language: python
group: travis_latest
dist: xenial
sudo: true

services:
  - xvfb

script:
  - service xvfb status         # we would expect the service is started - but it is not
  - sudo service xvfb start     # so start it manually
  - service xvfb status         # and check again
